name: nortus
description: "Loomi's technical challenge news app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0
  pretty_dio_logger: ^1.4.0
  go_router: ^15.1.2
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.0

flutter:

  uses-material-design: true
